services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
    volumes:
      - ./docker_data/wordpress:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: somerootpass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - ./docker_data/mariadb:/var/lib/mysql
