services:
  database:
    image: mariadb:11
    container_name: fiserv-woocommerce-db
    command: '--default-authentication-plugin=mysql_native_password'
    mem_limit: '256M'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - default
    volumes:
      - db:/var/lib/mysql
  apache:
    image: registry.gitlab.mherrm.de/cgi/fisrv-woocommerce-plugin:latest
    container_name: fisrv-woocommerce-apache
    mem_limit: '256M'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fiwoo-secure.entrypoints=http,https'
      - 'traefik.http.routers.fiwoo-secure.rule=Host(`fiwoo.mherrm.de`)'
      - 'traefik.http.routers.fiwoo-secure.tls=true'
      - 'traefik.http.routers.fiwoo-secure.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.fiwoo-secure.service=fiwoo'
      - 'traefik.http.services.fiwoo.loadbalancer.server.scheme=https'
      - 'traefik.http.services.fiwoo.loadbalancer.server.port=443'
      - 'traefik.docker.network=traefik'
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    networks:
      - default
      - traefik
networks:
  traefik:
    external: true
volumes:
  db:
