version: '3.8'

services:
  paypal:
    image: registry.gitlab.mherrm.de/cgi/fiserv-woocommerce-plugin:latest
    container_name: fiwoo
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fiwoo-secure.entrypoints=http,https"
      - "traefik.http.routers.fiwoo-secure.rule=Host(`fiwoo.mherrm.de`)"
      - "traefik.http.routers.fiwoo-secure.tls=true"
      - "traefik.http.routers.fiwoo-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.fiwoo-secure.service=fiwoo"
      - "traefik.http.services.fiwoo.loadbalancer.server.scheme=https"
      - "traefik.http.services.fiwoo.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - default
      - traefik
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 50M
networks:
  traefik:
    external: true

